# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'HLTH' do
  pod 'Moya'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
end